### PR TITLE
Adding docker-compose setup.

### PR DESCRIPTION
**Pull request by mschulkind**
I found the current setup process and container management a bit overwhelming. You'll probably want to reorganize this PR a bit, but with this, you can just clone this repo and then:

```
sudo pip install docker-compose
docker-compose up
```

Then just fire up postman (or the soon to be ruby client) and you're good to go.

This of course also assumes that you publish the omh-postgres image.

### CODE REVIEW

**Comment by emersonf** [comment]
I started looking into it this morning. :+1: I'll try to get to this by EOW.

**Comment by emersonf** [comment]
I was really hoping to find a way to run the script from Compose itself, instead of creating a database image, something along [these lines](https://github.com/docker/compose/issues/1341). I'm guessing people don't want their instances polluted with test data. Thoughts?

PS. The develop branch is more current.

**Comment by mschulkind** [comment]
I couldn't figure it out either with compose. I think your best options are:

1. Do nothing except what this PR does. I think it's very unlikely that
anybody will send this into production using the DB containers. They likely
won't even use the OMH containers.
2. Have the OMH containers init the database on startup if it hasn't
already been created.

**Comment by emersonf** [comment]
Merged into a25f819e424d8c62715f80064fa35d349065a4e9 on the feature/support-docker-compose branch, but I still need to add documentation. It's also set up to use `build` instead of `image` for quick development feedback. I'll add a binary-only compose file when I add docs.

**Comment by emersonf** [comment]
That red badge is misleading since it's been manually merged. I reopened it and will check if GitHub closes the pull request once the feature and develop get released.

**Pull request merged**
